module.exports.ENVIRONMENT_PRODUCTION = "production";
module.exports.ENVIRONMENT_DEVELOPMENT = "develop";
module.exports.MESSAGE_STATUS_TOBETREATED = "À traiter";
module.exports.MESSAGE_SCHEDULED_MINUTES = 15;
module.exports.CROSSKNOWLEDGE_STATUS_OK = "Y";
module.exports.CROSSKNOWLEDGE_LANGUAGE = "fr-FR";
module.exports.CROSSKNOWLEDGE_KONEXIO_ENTITY =
  "101B1F43-2D44-0AAC-CDA6-F4B8ED66F385";
module.exports.CROSSKNOWLEDGE_CUSTOMFIELDS_GROUP =
  "5BD8779F-BD3A-6F83-A44B-3CF77D67B2C2";
